name: 'ğŸ’… Lint GitHub Actions workflows'

on:
  push:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›¬
        uses: actions/checkout@v4
      - name: Download actionlint âš™ï¸
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) 1.6.26
        shell: bash
      - name: Check workflow files ğŸ’…ğŸ»
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
