name: 'ğŸ’… Lint PR Title'

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  main:
    name: Validate PR title ğŸ•µï¸
    runs-on: ubuntu-latest
    steps:
      - name: Validate pull request title ğŸ‘®ğŸ»
        uses: amannn/action-semantic-pull-request@v5
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ignoreLabels: |
            bot
            autorelease: pending
      - name: Write comment with error ğŸ’¬
        uses: marocchino/sticky-pull-request-comment@v2
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            Hey mate ğŸ‘‹. Thank you for opening this Pull Request ğŸ¤˜. It is really awesome to see this contribution ğŸš€

            ğŸ” When working with this project we are requesting to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted ğŸ¥¶.

            ğŸ‘‡ Bellow you can find details about what failed:

            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```

      - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        name: Delete comment ğŸ—‘ï¸
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          delete: true
